/**:
    ros__parameters:
        # not persistent parameter.
        some_int: 1
        a_string: "Hello world"
        pi: 3.14
        some_lists:
            some_integers: [1, 2, 3, 4]
        # persistent parameter.
        persistent:
            some_int: 1
            a_string: 'Hello world'
            pi: 3.14
            some_lists:
                some_integers: [1, 2, 3, 4]
